const previewProducts = [
	{
		image: './img/products/wood/slotted-serving-spoon.png',
		name: 'slotted serving spoon',
		price: '14.99',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/cloth/Upcycled-Cotton-Napkins.png',
		name: 'Upcycled Cotton Napkins',
		price: '3.95',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/silicon/silicon-bottle-2.png',
		name: 'bottle',
		price: '9.99',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/steel/brushed-stainless-bottle.png',
		name: 'brushed stainless bottle',
		price: '39.99',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/packaging-bag.png',
		name: 'packaging bag',
		price: '2.99',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/wood/tongs.png',
		name: 'tongs',
		price: '14.99',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/steel/Ekobo-cups.png',
		name: 'Ekobo cups',
		price: '7.45',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/silicon/silicon-toilet-brush-2.png',
		name: 'toilet brush',
		price: '7.33',
		category: 'silicon',
		quantity: 1,
	},
];

const allProducts = [
	{
		image: './img/products/wood/slotted-serving-spoon.png',
		name: 'slotted serving spoon',
		price: '14.99',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/wood/bowl.png',
		name: 'bowl',
		price: '5.39',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/wood/long-server.png',
		name: 'long server',
		price: '4.99',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/wood/tasting-spoon.png',
		name: 'tasting spoon',
		price: '1.99',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/wood/storagebin.webp',
		name: 'Storage Bin',
		price: '6.54',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/wood/chair.webp',
		name: 'Chair',
		price: '9.55',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/wood/comb.webp',
		name: 'Comb',
		price: '4.59',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/wood/toothbrush.webp',
		name: 'Tooth Brush',
		price: '3.15',
		category: 'wood',
		quantity: 1,
	},
	{
		image: './img/products/cloth/producebags.png',
		name: 'produce bag',
		price: '2.99',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/cloth/Cotton-Produce-Storage-Bag.png',
		name: 'Cotton Produce Storage Bag',
		price: '2.79',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/cloth/mesh-baggu-light-green.png',
		name: 'mesh baggu bag',
		price: '3.79',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/cloth/recyclebag.webp',
		name: 'Recycle Bag',
		price: '5.59',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/cloth/Skoy-Scrub-Cloth-2-Pack.png',
		name: 'Skoy Scrub Cloth',
		price: '5.99',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/cloth/Soap-Saver.png',
		name: 'soap saver',
		price: '1.49',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/cloth/baggu-four.png',
		name: 'baggu bag ',
		price: '3.49',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/cloth/Upcycled-Cotton-Napkins.png',
		name: 'Upcycled Cotton Napkins',
		price: '3.95',
		category: 'cloth',
		quantity: 1,
	},
	{
		image: './img/products/steel/brushed-stainless-bottle.png',
		name: 'brushed stainless bottle',
		price: '39.99',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/steel/Cambridge-reusable-crete.png',
		name: 'Cambridge reusable crete',
		price: '25.49',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/steel/Chilly.png',
		name: 'chilly',
		price: '17.89',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/steel/eco-lunch-box.png',
		name: 'eco lunch box',
		price: '54.49',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/steel/whisksilver.png',
		name: 'Whisk Silver',
		price: '3.29',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/steel/KeepCup.png',
		name: 'keep cup',
		price: '10.99',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/steel/razor.png',
		name: 'razor',
		price: '1.99',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/steel/spatula.png',
		name: 'spatula',
		price: '34.99',
		category: 'steel',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/biome-shampoo.png',
		name: 'biome shampoo',
		price: '13.88',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/celluloase-acetate-bottle.png',
		name: 'celluloase acetate bottle',
		price: '35.49',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/lipbalm.webp',
		name: 'Lip Balm',
		price: '3.76',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/papertape.webp',
		name: 'Paper Tape',
		price: '2.68',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/trash-bag.png',
		name: 'Trash Bag',
		price: '8.54',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/packaging-bag.png',
		name: 'packaging bag',
		price: '2.99',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/PLA-shampoobottlle.png',
		name: 'PLA shampoobottlle',
		price: '3.99',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/bioplastic/toilet-cleaning-bomb.png',
		name: 'toilet cleaning bomb',
		price: '2.99',
		category: 'bioplastic',
		quantity: 1,
	},
	{
		image: './img/products/silicon/silicon-bottle-2.png',
		name: 'bottle a',
		price: '9.99',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/silicon/silicon-glove-2.png',
		name: 'glove a',
		price: '5.99',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/silicon/siliconplate.png',
		name: 'plate',
		price: '2.45',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/silicon/bathingbrush1.webp',
		name: 'Bathing Brush',
		price: '3.99',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/silicon/silicon-toilet-brush.png',
		name: 'toilet brush a',
		price: '6.89',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/silicon/silicon-glove-3.png',
		name: 'glove b',
		price: '2.49',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/silicon/foodcover.png',
		name: 'Food Cover',
		price: '4.49',
		category: 'silicon',
		quantity: 1,
	},
	{
		image: './img/products/silicon/silicon-bottle.png',
		name: 'bottle b',
		price: '7.99',
		category: 'silicon',
		quantity: 1,
	},
];
